# Generated by Django 4.1.3 on 2023-06-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_doctor_email_alter_doctor_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='document',
            field=models.FileField(blank=True, upload_to='media/doctor_document'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/doctor_photo'),
        ),
    ]
