# Generated by Django 4.2.1 on 2023-06-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_doctor_document_alter_doctor_photo'),
        ('account', '0003_rename_first_name_doctor_first_name_and_more'),
    ]

    operations = [
    ]
