# Generated by Django 4.2.1 on 2023-06-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_merge_20230602_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='document',
            field=models.FileField(upload_to='media/doctor_document'),
        ),
    ]
