# Generated by Django 4.2.1 on 2023-06-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_doctor_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_admin',
            field=models.BooleanField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_patient',
            field=models.BooleanField(default=False, max_length=5),
        ),
    ]
