# Generated by Django 4.2.1 on 2023-06-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_revoke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revoke',
            name='code',
            field=models.CharField(blank=True, default='POST:XkeFY', max_length=15),
        ),
        migrations.AlterField(
            model_name='revoke',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.doctor'),
        ),
        migrations.AlterField(
            model_name='revoke',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.patient'),
        ),
    ]
