# Generated by Django 4.2.1 on 2023-06-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_revoke_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Dermatologist', 'Dermatologist'), ('Dentist', 'Dentist'), ('Sexologist', 'Sexologist'), ('Dietitian/Nutritionist', 'Dietitian/Nutritionist'), ('General Physician', 'General Physician'), ('Orthopedist', 'Orthopedist'), ('Gynaecologist', 'Gynaecologist'), ('Pediatrics', 'Pediatrics'), ('Psychologist', 'Psychologist'), ('General practitioner', 'General practitioner')], max_length=100),
        ),
    ]
